# Generated by Django 4.0.2 on 2022-02-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField()),
                ('short_link', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('lifetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
